apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nginx.127.0.0.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80


              
              #kubectl apply -f nginx-ingress.yaml
#test : kubectl get ingress
#http://nginx.127.0.0.1.nip.io
# create : nginx.127.0.0.1.nip.io


