apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-demo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP


#apply svc : kubectl apply -f nginx-svc.yaml
